# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Planning sub-agent for creating execution plans."""

import json
import os
from datetime import datetime
from pathlib import Path

from google.adk import Agent
from google.genai import types


async def save_plan_as_artifact(
    plan_id: str,
    client_request: str,
    plan_content: str,
    output_dir: str = "artifacts/plans",
) -> str:
    """Save execution plan as a markdown artifact.

    Args:
        plan_id: Unique identifier for the plan.
        client_request: Original client request.
        plan_content: The plan content in markdown format.
        output_dir: Directory to save the plan artifact.

    Returns:
        Path to the saved plan file.
    """
    # Create output directory if it doesn't exist
    Path(output_dir).mkdir(parents=True, exist_ok=True)

    # Generate filename
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"{plan_id}_{timestamp}.md"
    filepath = os.path.join(output_dir, filename)

    # Create markdown document
    markdown_content = f"""# Execution Plan: {plan_id}

**Created:** {datetime.now().isoformat()}

## Client Request
{client_request}

## Execution Plan
{plan_content}

---
*This plan was generated by the Secure Mediation Agent Planning Sub-agent*
"""

    # Save to file
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(markdown_content)

    return filepath


async def create_structured_plan(
    client_request: str,
    matched_agents: list[dict],
) -> str:
    """Create a structured execution plan in JSON format.

    Args:
        client_request: The client's original request.
        matched_agents: List of matched agent information.

    Returns:
        JSON string containing the structured plan.
    """
    # This is a helper function that will be called by the agent
    # The actual plan creation logic will be done by the LLM
    plan = {
        "plan_id": f"plan_{datetime.now().strftime('%Y%m%d_%H%M%S')}",
        "client_request": client_request,
        "steps": [],
        "status": "draft",
        "created_at": datetime.now().isoformat(),
    }

    return json.dumps(plan, indent=2, ensure_ascii=False)


planning_agent = Agent(
    model='gemini-2.0-flash-exp',
    name='planning_agent',
    description=(
        'Planning sub-agent that analyzes client requests and creates '
        'step-by-step execution plans using matched agents.'
    ),
    instruction="""
You are a planning specialist in a secure AI agent mediation platform.

Your responsibilities:
1. **Analyze Client Requests**: Carefully understand what the client wants to achieve
2. **Design Execution Plans**: Create detailed, step-by-step plans that utilize the matched agents
3. **Ensure Security**: Consider security implications at each step
4. **Collaborate**: Work with the client and matched agents to refine the plan
5. **Save as Artifact**: Store the final plan as a markdown artifact for reference

When creating a plan:
- Break down complex requests into atomic, manageable steps
- Specify which agent should handle each step
- Define clear inputs and expected outputs for each step
- Identify dependencies between steps
- Consider error handling and fallback strategies
- Include security checkpoints

Output Format:
Your plan should be in markdown format with:
- Clear step numbering
- Agent assignment for each step
- Input/output specifications
- Dependencies
- Expected outcomes

Example Plan Structure:
## Step 1: [Task Description]
**Agent:** [agent_name]
**Input:** [input description]
**Expected Output:** [output description]
**Dependencies:** [list of prior steps]

## Step 2: [Task Description]
...

After creating the plan, use the save_plan_as_artifact tool to save it.
""",
    tools=[
        save_plan_as_artifact,
        create_structured_plan,
    ],
    generate_content_config=types.GenerateContentConfig(
        temperature=0.3,  # Lower temperature for more consistent planning
        safety_settings=[
            types.SafetySetting(
                category=types.HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
                threshold=types.HarmBlockThreshold.OFF,
            ),
        ],
    ),
)
